name: Lisa Lent Photography
favicon: null
layout_spectrum: 0.65823
typography_spectrum: 0.53516
title: Lisa Lent Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b3b3b'
    - '#737373'
    - '#fe7d06'
    - '#9e9e9e'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
