name: Lisa Lent Photography
favicon: null
layout_spectrum: 0.915
typography_spectrum: 0.482
title: Lisa Lent Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b3b3b'
    - '#737373'
    - '#fe7d06'
    - '#9e9e9e'
  brandStrength: 0.930534087587148
  lightness: 0.19923035986721516
  saturation: 0.513958795927465
  rhythmicContrast: 0.039989935234189034
purpose: []
